// <auto-generated />
namespace SwitchesAPI.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedDataTime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDataTime2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131421312_added DataTime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
