// <auto-generated />
namespace SwitchesAPI.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Init_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201801020109192_Init_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
